#!/bin/bash

singularity exec --bind $masurcagit:/mnt --bind $PWD $masurcagit/SIMG/ISUGIFsingularity-masurca-master.simg $@
#singularity exec --bind $PWD --bind $TMPDIR  $masurcagit/SIMG/ISUGIFsingularity-masurca-master-1.0.0.simg $@
